use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub enum ShowStatus {
    Running,
    Ended,
    #[serde(rename = "To Be Determined")]
    ToBeDetermined,
    #[serde(rename = "In Development")]
    InDevelopment,
}

#[derive(Deserialize, Debug)]
pub enum ShowType {
    Scripted,
    Animation,
    Reality,
    #[serde(rename = "Talk Show")]
    TalkShow,
    Documentary,
    #[serde(rename = "Game Show")]
    GameShow,
    News,
    Sports,
    Variety,
    #[serde(rename = "Award Show")]
    AwardShow,
    #[serde(rename = "Panel Show")]
    PanelShow,
}

#[derive(Deserialize, Debug)]
pub enum Genre {
    Action,
    Adult,
    Adventure,
    Anime,
    Children,
    Comedy,
    Crime,
    DIY,
    Drama,
    Espionage,
    Family,
    Fantasy,
    Food,
    History,
    Horror,
    Legal,
    Medical,
    Music,
    Mystery,
    Nature,
    Romance,
    #[serde(rename = "Science-Fiction")]
    ScienceFiction,
    Sports,
    Supernatural,
    Thriller,
    Travel,
    War,
    Western,
}

#[derive(Deserialize, Debug)]
pub enum Language {
    Afrikaans,
    Albanian,
    Arabic,
    Armenian,
    Azerbaijani,
    Basque,
    Belarusian,
    Bengali,
    Bosnian,
    Bulgarian,
    Catalan,
    Chechen,
    Chinese,
    Croatian,
    Czech,
    Danish,
    Divehi,
    Dutch,
    English,
    Estonian,
    Finnish,
    French,
    Galician,
    Georgian,
    German,
    Greek,
    Gujarati,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Indonesian,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Kongo,
    Korean,
    Latin,
    Latvian,
    Lithuanian,
    Luxembourgish,
    Malay,
    Malayalam,
    Marathi,
    Mongolian,
    Norwegian,
    Panjabi,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    Romanian,
    Russian,
    Serbian,
    Sinhalese,
    Slovak,
    Slovenian,
    Spanish,
    Swahili,
    Swedish,
    Tagalog,
    Tamil,
    Telugu,
    Thai,
    Turkish,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Welsh,
    #[serde(rename = "Scottish Gaelic")]
    ScottishGaelic,
}
